name: Build and Upload Artifacts

on:
  push:
    branches:
      - artifact
  pull_request:
   #branches:
   #  - main
   #  - master

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pictopy_linux'

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pictopy_windows'

  osx-arm-build:
    runs-on: macos-13
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'pictopy_osx'

  android-build:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy pywebview-android.jar
        run: |
          pip install pywebview
          python -c "import webview.util; import shutil; shutil.copy(webview.util.android_jar_path(), 'pywebview-android.jar')"

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ./
          buildozer_version: stable

      - name: UploadArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android
          path: ${{ steps.buildozer.outputs.filename }}
